controller:
  replicaCount: 2
  service:
    externalTrafficPolicy: "Local"
  metrics:
    enabled: false
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
    serviceMonitor:
      enabled: false
      namespaceSelector:
        any: true
  extraArgs:
    # Enable use of annotation
    # nginx.ingress.kubernetes.io/ssl-passthrough
    enable-ssl-passthrough: ""
