ingress:
  enabled: true
  tls:
    - secretName: oauth2-proxy-ingress-tls
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi
replicaCount: 2
extraEnv:
- name: OAUTH2_PROXY_SET_XAUTHREQUEST
  value: "true"
extraArgs:
  silence-ping-logging: true
